// 手机同步协议：电脑连接器与手机 App 共用。设计见 docs/mobile-sync.md。

export {
  COMPRESS_THRESHOLD_BYTES,
  MAX_PLAINTEXT_BYTES,
  SPACE_SECRET_BYTES,
  deriveSpaceKeys,
  projectHash,
  type SpaceKeys,
} from "./crypto.js";
export { fromBase64Url, toBase64Url } from "./encoding.js";
export {
  MAX_PARTS,
  PART_CHARS,
  openObject,
  parseHeadEnvelope,
  sealObject,
  type HeadEnvelope,
  type PartEnvelope,
  type SealedPart,
} from "./envelope.js";
export { SyncProtocolError, isSyncProtocolError, type SyncProtocolErrorCode } from "./errors.js";
export { ChangeFeed, backoffDelay, type ChangeFeedOptions, type FeedBatch } from "./feed.js";
export {
  APP_ID_PATTERN,
  COMMAND_ID_PATTERN,
  DEVICE_ID_PATTERN,
  DOC_KEY_PATTERN,
  KEY_PREFIX,
  PROJECT_CODE_PATTERN,
  PROJECT_HASH_PATTERN,
  SPACE_ID_PATTERN,
  TASK_KEY_PATTERN,
  ackKey,
  classifyKey,
  commandKey,
  commandTimestamp,
  deviceKey,
  headKey,
  newCommandId,
  newDeviceId,
  newSpaceId,
  partKey,
  projectKey,
  revokedKey,
  spacePrefix,
  type ClassifiedKey,
  type DeviceKind,
  type KeyKind,
} from "./keys.js";
export {
  PAIRING_PREFIX,
  PairingPayloadSchema,
  decodePairingCode,
  encodePairingCode,
  generateSpace,
  normalizeRelayUrl,
  type NewSpace,
  type PairingPayload,
} from "./pairing.js";
export {
  RelayClient,
  RelayError,
  type FetchLike,
  type FetchLikeInit,
  type FetchLikeResponse,
  type RelayChange,
  type RelayChangesPage,
  type RelayClientOptions,
  type RelayConflictCurrent,
  type RelayDocument,
  type RelayDocumentMeta,
  type RelayErrorCode,
  type RelayProbe,
} from "./relay-client.js";
export {
  AckDocSchema,
  COMMAND_MAX_AGE_MS,
  CommandDocSchema,
  DISPATCH_STATES,
  DeviceDocSchema,
  HOST_ONLINE_WINDOW_MS,
  HeadDocSchema,
  PERMISSION_MODES,
  ProjectDocSchema,
  ProjectHeadSchema,
  RevokedDocSchema,
  TASK_PRIORITIES,
  TASK_STATUSES,
  TASK_TYPES,
  TaskCardSchema,
  TaskCreateBodySchema,
  TaskDispatchBodySchema,
  type AckDoc,
  type CommandDoc,
  type CommandInput,
  type DeviceDoc,
  type HeadDoc,
  type ProjectCounts,
  type ProjectDoc,
  type ProjectHead,
  type RevokedDoc,
  type TaskCard,
  type TaskCreateBody,
  type TaskDispatchBody,
} from "./schemas.js";
export { SpaceStore, type SpaceStoreOptions } from "./space-store.js";
